package com.ferrumlabs.enums;

public enum ChristianSpecialDatesEnum {
	FIRST_SUNDAY_ADVENT("First Sunday of Advent"),
	SECOND_SUNDAY_ADVENT("Second Sunday of Advent"),
	THIRD_SUNDAY_ADVENT("Third Sunday of Advent"),
	FOURTH_SUNDAY_ADVENT("Forth Sunday of Advent"),
	CHRISTMAS_EVE("Christmas Eve"),
	CHRISTMAS_DAY("Christmas Day"),
	FIRST_SUNDAY_CHRISTMAS("First Sunday After Christmas"),
	HOLY_NAME_JESUS("Feast of the Holy Name of Jesus"),
	NEW_YEARS_DAY("New Years Day"),
	SECOND_SUNDAY_CHRISTMAS("Second Sunday After Christmas"),
	EPIPHANY("Epiphany of the Lord"),
	FIRST_SUNDAY_EPIPHANY("First Sunday of Epiphany"),
	SECOND_SUNDAY_EPIPHANY("Second Sunday of Epiphany"),
	THIRD_SUNDAY_EPIPHANY("Third Sunday of Epiphany"),
	FOURTH_SUNDAY_EPIPHANY("Fourth Sunday of Epiphany"),
	FIFTH_SUNDAY_EPIPHANY("Fifth Sunday of Epiphany"),
	SIXTH_SUNDAY_EPIPHANY("Sixth Sunday of Epiphany"),
	SEVENTH_SUNDAY_EPIPHANY("Seventh Sunday of Epiphany"),
	EIGHTH_SUNDAY_EPIPHANY("Eighth Sunday of Epiphany"),
	NINTH_SUNDAY_EPIPHANY("Ninth Sunday of Epiphany"),
	PRESENTATION_JESUS("Presentation of Jesus at the Temple"),
	TRANSFIGURATION_SUNDAY("Transfiguration Sunday"),
	ASH_WEDNESDAY("Ash Wednesday"),
	FIRST_SUNDAY_LENT("First Sunday of Lent"),
	SECOND_SUNDAY_LENT("Second Sunday of Lent"),
	THIRD_SUNDAY_LENT("Third Sunday of Lent"),
	FOURTH_SUNDAY_LENT("Fourth Sunday of Lent"),
	FIFTH_SUNDAY_LENT("Fifth Sunday of Lent"),
	PALM_SUNDAY("Palm Sunday"),
	MONDAY_HOLY_WEEK("Monday of Holy Week"),
	TUESDAY_HOLY_WEEK("Tuesday of Holy Week"),
	WEDNESDAY_HOLY_WEEK("Wednesday of Holy Week"),
	MAUNDY_THURSDAY("Maundy Thursday"),
	GOOD_FRIDAY("Good Friday"),
	HOLY_SATURDAY("Holy Saturday"),
	EASTER_VIGIL("Easter Vigil"),
	EASTER("Easter"),
	SECOND_SUNDAY_EASTER("Second Sunday of Easter"),
	ANNUNCIATION_LORD("Annunciation of the Lord"),
	THIRD_SUNDAY_EASTER("Third Sunday of Easter"),
	FOURTH_SUNDAY_EASTER("Fourth Sunday of Easter"),
	FIFTH_SUNDAY_EASTER("Fifth Sunday of Easter"),
	SIXTH_SUNDAY_EASTER("Sixth Sunday of Easter"),
	ASCENSION("Ascension of the Lord"),
	ASCENSION_SUNDAY("Ascension Sunday"),
	SEVENTH_SUNDAY_EASTER("Seventh Sunday of Easter"),
	PENTECOST("Pentecost"),
	VISITATION_MARY("Feast of Visitation of Mary to Elizabeth"),
	HOLY_CROSS("Feast of the Cross"),
	TRINITY_SUNDAY("Trinity Sunday"),
	SECOND_SUNDAY_PENTECOST("Second Sunday after Pentecost"),
	THIRD_SUNDAY_PENTECOST("Third Sunday after Pentecost"),
	FOURTH_SUNDAY_PENTECOST("Fourth Sunday after Pentecost"),
	FIFTH_SUNDAY_PENTECOST("Fifth Sunday after Pentecost"),
	SIXTH_SUNDAY_PENTECOST("Sixth Sunday after Pentecost"),
	SEVENTH_SUNDAY_PENTECOST("Seventh Sunday after Pentecost"),
	EIGHTH_SUNDAY_PENTECOST("Eighth Sunday after Pentecost"),
	NINTH_SUNDAY_PENTECOST("Ninth Sunday after Pentecost"),
	TENTH_SUNDAY_PENTECOST("Tenth Sunday after Pentecost"),
	ELEVENTH_SUNDAY_PENTECOST("Eleventh Sunday after Pentecost"),
	TWELFTH_SUNDAY_PENTECOST("Twelfth Sunday after Pentecost"),
	THIRTEENTH_SUNDAY_PENTECOST("Thirteenth Sunday after Pentecost"),
	FOURTHEENTH_SUNDAY_PENTECOST("Fourteenth Sunday after Pentecost"),
	FIFTHEENTH_SUNDAY_PENTECOST("Fifteenth Sunday after Pentecost"),
	SIXTHEENTH_SUNDAY_PENTECOST("Sixteenth Sunday after Pentecost"),
	SEVENTEENTH_SUNDAY_PENTECOST("Seventeenth Sunday after Pentecost"),
	EIGHTEENTH_SUNDAY_PENTECOST("Eighteenth Sunday after Pentecost"),
	NINTEENTH_SUNDAY_PENTECOST("Ninteenth Sunday after Pentecost"),
	TWENTIETH_SUNDAY_PENTECOST("Twentieth Sunday after Pentecost"),
	TWENTY_FIRST_SUNDAY_PENTECOST("Twenty-First Sunday after Pentecost"),
	TWENTY_SECOND_SUNDAY_PENTECOST("Twenty-Second Sunday after Pentecost"),
	TWENTY_THIRD_SUNDAY_PENTECOST("Twenty-Third Sunday after Pentecost"),
	TWENTY_FOURTH_SUNDAY_PENTECOST("Twenty-Fourth Sunday after Pentecost"),
	TWENTY_FIFTH_SUNDAY_PENTECOST("Twenty-Fifth Sunday after Pentecost"),
	TWENTY_SIXTH_SUNDAY_PENTECOST("Twenty-Sixth Sunday after Pentecost"),
	TWENTY_SEVENTH_SUNDAY_PENTECOST("Twenty-Seventh Sunday after Pentecost"),
	CHRIST_IS_KING("Christ is King Sunday"),
	ALL_SAINTS_DAY("All Saints Day"),
	CANADIAN_THANKSGIVING("Canadian Thanksgiving Day"),
	USA_THANKSGIVING("Thanksgiving Day");
	
	private String displayName;
	
	ChristianSpecialDatesEnum(String displayName){
		this.displayName=displayName;
	}
	
	public String getDisplayName(){
		return this.displayName;  
	}
	
}
